//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogPencereleri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int ID { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> Kategori { get; set; }
        public Nullable<int> AltKategori { get; set; }
        public string Kod { get; set; }
        public Nullable<int> Tur { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> SatisBaslangicTarihi { get; set; }
        public string SatisFiyati { get; set; }
        public string KDVOrani { get; set; }
        public Nullable<int> GuvenlikStogu { get; set; }
        public string ABCSinifi { get; set; }
        public string Olcu_En { get; set; }
        public string Olcu_Boy { get; set; }
        public string Olcu_Yukseklik { get; set; }
        public string Olcu_Hacim { get; set; }
        public string Olcu_Agirlik { get; set; }
        public string Olcu_NetAgirlik { get; set; }
        public string Barkod { get; set; }
    
        public virtual AltKategoriler AltKategoriler { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual UrunTuru UrunTuru { get; set; }
    }
}
